spring:
  application:
    name: deliverypartner
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/food_deliverypartnerdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: deliverypartner-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.foodapp.deliverypartner.model.Customer
        spring.json.trusted.packages: "*"

server:
  port: 2002

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:4002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

jwt:
  secret: uY9FJ3V0sKQe7mR2xB8A6ZpNwH1L4C5TtE0dSgOaXyI=
  expiration: 900000

info:
  app:
    name: "deliverypartner"