spring:
  application:
    name: restaurant
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://restaurantdb:27017/food_restaurantdb
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: restaurant-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.foodapp.restaurant.model.Customer
        spring.json.trusted.packages: "*"

server:
  port: 2004

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:4002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

jwt:
  secret: uY9FJ3V0sKQe7mR2xB8A6ZpNwH1L4C5TtE0dSgOaXyI=
  expiration: 900000

info:
  app:
    name: "customer"